repos:
  - repo: https://github.com/doublify/pre-commit-rust
    rev: eeee35a89e69d5772bdee97db1a6a898467b686e  # frozen: v1.0
    hooks:
      # - id: fmt
      - id: clippy
        args: ["--all", "--all-features"]
      - id: cargo-check
  # Implement fmt by hand since above hook seems to have problems recognizing the Rust edition.
  - repo: local
    hooks:
    - id: fmt
      name: fmt
      language: system
      entry: cargo fmt --all
      files: \.rs$
      pass_filenames: false
  - repo: https://github.com/jorisroovers/gitlint
    rev: acc9d9de6369b76d22cb4167029d2035e8730b98  # frozen: v0.19.1
    hooks:
      - id: gitlint
  - repo: https://github.com/crate-ci/typos
    rev: cf5f1c29a8ac336af8568821ec41919923b05a83  # frozen: v1.45.1
    hooks:
      - id: typos
        exclude: "vscode/package-lock.json"
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: e72a3ca1632f0b11a07d171449fe447a7ff6795e  # frozen: v0.48.0
    hooks:
      - id: markdownlint-fix
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 3e8a8703264a2f4a69428a0aa4dcb512790b2c8c  # frozen: v6.0.0
    hooks:
      - id: trailing-whitespace
        exclude: "^tests/Baseline"
      - id: end-of-file-fixer
        exclude: "^tests/Baseline|^doc/autogen|^doc/_static"
      - id: check-yaml
      - id: check-added-large-files
  - repo: https://github.com/rhysd/actionlint
    rev: 914e7df21a07ef503a81201c76d2b11c789d3fca  # frozen: v1.7.12
    hooks:
      - id: actionlint
  - repo: https://github.com/biomejs/pre-commit
    rev: c5371526e61a7350476d9eb51ccc6a8251e6ee8d  # frozen: v2.4.13
    hooks:
      - id: biome-format
      - id: biome-lint

exclude: "(.github/workflows/release.yml|src/snapshots/)"
